# Generated by Django 2.1.10 on 2020-04-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phylodating', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
