# Generated by Django 2.2 on 2020-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylodating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='warnings',
            field=models.TextField(default=None),
        ),
    ]
